# main text of home
name: Luke Metz
bio: Machine Learning, Robotics, Making

# twitter summary info
description: description?

# if it's an external image, update below for true
# better with square images
external-image: false
picture: assets/images/me.png

# If you want to include your resume, set to true
# and specify source (external or local).
resume: false
resume-external: true
resume-url: https://google.com/?q=my+resume

publications: true

url: https://lukemetz.github.io

permalink: /:title/

# To enable google analytics, supply your token below
analytics-google: 'UA-112984812-1'

# To enable piwik tracking, supply your url & site ID below
# analytics-piwik-url: 'piwik.my-host.com'
# analytics-piwik-id: 1

# if you don't want comments in your posts, leave categories empty
disqus:
  shortname: lukemetz-com
  categories: [blog, project] # only show disqus for posts that have these categories

# if you don't have any of social below, comment the line
#facebook: myfacebook
twitter: Luke_Metz
# google: mygoogle
# instagram: myinstagram
# pinterest: mypinterest
linkedin: luke-metz-5003046a
# youtube: myyoutube
# spotify: myspotify
github: lukemetz
# lastfm: mylastfm
# stackoverflow: 7044681/mystackoverflow
# quora: userquora
# reddit: username
# medium: medium
# vimeo: myvimeo
# lanyrd: mylanyrd
email: luke.s.metz@gmail.com

authors:
    lukemetz:
        name: Luke Metz
        # bio: A Man who travels the world eating noodles
        external-image: false
        picture: assets/images/me.png
        twitter: Luke_Metz

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: normal

# if you don't need pagination, comment the *paginate* configs below
# paginate: 5
# paginate_path: "blog/:num/"

# if you don't need projects, comment the *projects* configs below
projects: true

# if you don't need "about" or "blog", comment them out below
about: true
blog: true
publications: true

# do you want to show the "read time" of the posts?
read-time: true

# do you want to show the "tags" inside the posts?
show-tags: true

# related posts inside a post?
related: true

# Display links for next and previous posts for the specified categories
post-advance-links: [blog]

# show author block at the end of a post ?
show-author: true

# do you want some animations?
animation: false

plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-admin

jekyll-mentions:
    base_url: https://github.com

publications_list:
  - year_split: true
    year: 2019
  - title: Meta-Learning Update Rules for Unsupervised Representation Learning
    people:
      - Luke Metz
      - Brian Cheung
      - Niru Maheswaranathan
      - Jascha Sohl-Dickstein
    arxiv: http://metalearning.ml/papers/metalearn17_metz.pdf
    location: ICLR 2019 (oral), COSYNE 2018 (oral), NeurIPS 2017 metalearning workshop

  - title: Towards GAN Benchmarks Which Require Generalization 
    people:
      - Ishaan Gulrajani 
      - Colin Raffel
      - Luke Metz
    location: ICLR 2019

  - year_split: true
    year: 2018

  - title: Learned optimizers that outperform SGD on wall-clock and validation loss
    people:
      - Luke Metz
      - Niru Maheswaranathan
      - Jeremy Nixon
      - C. Daniel Freeman
      - Jascha Sohl-Dickstein
    location: NeurIPS 2018 metalearning workshop
    arxiv: https://arxiv.org/pdf/1810.10180.pdf

  - title: "Guided evolutionary strategies: escaping the curse of dimensionality in random search"
    people:
      - Niru Maheswaranathan
      - Luke Metz
      - George Tucker
      - Jascha Sohl-Dickstein
    arxiv: https://arxiv.org/pdf/1806.10230.pdf

  - title: Adversarial Spheres
    people:
      - Justin Gilmer
      - Luke Metz
      - Fartash Faghri
      - Samuel S Schoenholz
      - Maithra Raghu
      - Martin Wattenberg
      - Ian Goodfellow
    arxiv: https://arxiv.org/pdf/1801.02774

  - year_split: true
    year: 2017

  - title: Compositional Pattern Producing GAN
    people:
      - Luke Metz
      - Ishaan Gulrajani
    arxiv: https://nips2017creativity.github.io/doc/CPPNGAN.pdf
    location: NeurIPS 2017 creativity workshop

  - title: Discrete Sequential Prediction of Continuous Actions for Deep RL
    people:
      - Luke Metz
      - Julian Ibarz
      - Navdeep Jaitly
      - James Davidson
    arxiv: https://arxiv.org/pdf/1705.05035

  - title: "Began: Boundary Equilibrium Generative Adversarial Networks"
    people:
      - David Berthelot
      - Tom Schumm
      - Luke Metz
    arxiv: https://arxiv.org/pdf/1703.10717

  - title: Unrolled Generative Adversarial Networks
    people:
      - Luke Metz
      - Ben Poole
      - David Pfau
      - Jascha Sohl-Dickstein
    location: ICLR 2017
    arxiv: https://arxiv.org/abs/1611.02163

  - year_split: true
    year: 2016
  - title: Unsupervised Representation Learning With Deep Convolutional Generative Adversarial Networks
    people:
      - Alec Radford
      - Luke Metz
      - Soumith Chintala
    location: ICLR 2016
    arxiv: https://arxiv.org/abs/1511.06434
